-- SQLite
--

SELECT * FROM RECEITAS_RECEITA WHERE INGREDIENTS LIKE '%CHOCOLATE%'
--SELECT CT.APP_LABEL, P.* FROM AUTH_PERMISSION P INNER JOIN DJANGO_CONTENT_TYPE CT
--SELECT * FROM AUTH_USER
--SELECT * FROM DJANGO_MIGRATIONS
--SELECT * FROM DJANGO_SESSION