# Generated by Django 5.2.5 on 2025-09-16 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0002_alter_receita_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='categoria',
            field=models.CharField(choices=[('comida', 'Comida'), ('sobremesa', 'Sobremesa'), ('drink', 'Drink')], default='comida', max_length=20, verbose_name='Categoria'),
        ),
    ]
